apiVersion: v1
entries:
  kserve:
  - apiVersion: v1
    created: "2023-08-14T13:05:41.0522712+02:00"
    description: Helm chart for deploying kserve resources
    digest: 88d53fc169ee311d01e877c96ffa4ec21496bd97f0880b3daaa8db50c3513f62
    keywords:
    - kserve
    - modelmesh
    name: kserve
    sources:
    - http://github.com/kserve/kserve
    urls:
    - https://github.com/Nibleash/kserve-helm/kserve-v0.11.0.tgz
    version: v0.11.0
  kserve-crd:
  - apiVersion: v1
    created: "2023-08-14T13:05:41.0508198+02:00"
    description: Helm chart for deploying kserve crds
    digest: 201fc9464736474889813357f708a198aa6aedb6269aa6060fd5a51f6fcca3ce
    keywords:
    - kserve
    - modelmesh
    name: kserve-crd
    sources:
    - http://github.com/kserve/kserve
    urls:
    - https://github.com/Nibleash/kserve-helm/kserve-crd-v0.11.0.tgz
    version: v0.11.0
generated: "2023-08-14T13:05:41.0296609+02:00"
